language: node_js
node_js:
- '10'
sudo: required
services:
- docker
- mongodb
script:
- npm run test
deploy:
  provider: gae
  project: order-api-226821
  keyfile: gce.json
  skip_cleanup: true
  verbosity: debug
  on: master
env:
  global:
  - secure: jRv5KWiUjwqMZ5Hk9k7XLIARKfKnlYdFFJBLkCt8w4A9aMPJzeX9D+KXnsNzP8QYJLhH8Z6rZmDfN4QwPHTAghzbJ/ATyXWyfJANA8d0ZiW+qlmHwUP0bWW3IA8UZBcHHKSUFaYOBExgTV7kmDDJTaGaOBXSr5TfuTWhQoerhLajeHtv1nxmNsh09QmRW9QKakq1P47cEIb5z/bFBjYLQJNwiNRvqCH1zhBDAtzErAVjYjeUeeHz+seduhcENsaYOjG1nwnfkwsrM41BX9BdVLOIyGNhFTr/pRyBjkuAkcM1uHO3FmeiLjDQZo7V41i8svdgB6JR5/5s5ZafWCejltc6tXCvH5cBOZXlRfvDFHrb3nNkA8rdo6sePgc0UeETdi6THx+DGQNgxeLUG9ftvEhilpw4vpatZKSVz6PgWjvMg8q9MYquARLbfL9jrgDl3u3flCF+Dy9qg/Ufpz1JK2pALgghLn7yC4LwLWZOQ/J93GR91FHjJ/YG4xFTPLlhr0pL2+wYTyKkuUFLzaohKltK0MaR1zeaZH5nEg9h+wYB65lstGPMyMtERR3tyN/vomWNOb/CgwkDy3vRw/crk1UbfHUwGpEhKBRbUnZRrO9h7Fjjx+opdiUy1iAOjgldnOlkZnP/WWrDBtk+Pj3hl0p6GYpmcqMXVrAaxTxZPiM=
  - secure: VcZNisHv/1jXFiABUF8HQAmMPyLe+z/jud+nHtwUn6cb9pL5N3OgMPxLwjkT4m+BcTesjf8GvxmaIu7DYSMRPtq05dxBuKxtAQkYSrGCIciZTB4En138Wwt6IU6PD5CQaQtu3kD+x/jzzbVhiOAqpYgkXX8F84XnGXDkqdyD3ZE5JqGVyVjw3YqKAKFVhLfqEFwHPkF1I2urqHf8uR4d+pialG8gyWMJnPLyzKun5qsBiEg2YTkIBVSw7cTvt1LY7/3ij8H8vqTQEPRjNQJfmXnfU3beEWUXtFo6KFa9Qxf2ZWJFMMz9BVZXWammLWYIfrl1rbFQENxvE/iIcgP4uSALf9A6oDURl8uUhFm7v6gpZUasR9PdregZ5SBRjDWAy0GhwkrRni5ptrFqKaAwuwp5XVgjO/OFGT5IWsLfehP1n9vnnUTraO+C9OGt1MheoXjV5BsrRITmZXYxDOQvDfAQsRMdxCFAQnHcpz69cNUTiTNYG9qA5qYWjptIkKOSzX4RwnAZGvw98qC5efYaV38o9KyX6kLGVMlTgNbDTFMo9+bkg5GGw7kmJT9bbUQEND4gVMJYVJ143/igvy5KP5MvhHKE5JtKNjNT0tTtBHa1n9iSRyjxIsKWjsPbULW3DQh8nKvC2ECP8efdbpLaiMgr34IxflJKH1s6r8MOVg0=
  - secure: HZZqr7idokG+HmLg+UiaiMcLio/203RQS8q/aAch8zR6CpdWRWt2n62fwXQofOzjS73ctD5rSbdxz+YQYt3RqPrW8Wa7B5Wwe9JFhgsQvGKZ79q08IgkcrjRrbseAJDIRcyLKm88XrAZMrceiwxrHF/bJsorW1mdUQAcDFjfKpN/QekL5AZoibQB119mZ+/1nbdB86zYocbSUOgOfUwX5nOpX64yk1NjIhIpcbLJIO4TZpwsWiQGklCmaNhvHGzOx6cl7rOYxAXnKMOI3gnS0OBr1XnzyRgUJYZWbQ3Ljt8UrffaUWoafaVcPVQ9BnT7v9+/M9G8Qb9v/emHUbcz3/2aethdLWcvcpGWxEaNctQfPybZlKAp3kRquLzvSj/vqrInMyNhsC3gWTwywsM8mnzkVFBH7HPb3SZAj2WcZGyDT6ymwwbEtN50i6ROL81trK/J0BV15b2wv66mPc/8xqxGkXf6EVp4LDrRSNIqgUYPz0bkYctUeDo/rbEnsh5+GZ0u93S9xne9/BzzjhbwrSJplpXCYw+na+gnxjgQBcN8Nhn+p+UjaByZ+RBlASDdANxsCa7XLFNnrG975oWy6xC4FjSyomtPtfTJVM1IEsSQ0xMMvLjl+JusJaPVPhkLhMu0s9/GDNid/dF4Pw5w4JFUMRNA9IAZOHQKLGWQfUM=
before_install:
- openssl aes-256-cbc -K $encrypted_5c02ebcbdbd5_key -iv $encrypted_5c02ebcbdbd5_iv
  -in gce.json.enc -out gce.json -d
